import React, {createContext, useContext, useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {defineCatalog} from '@json-render/core';
import {schema} from '@json-render/react/schema';
import {defineRegistry, JSONUIProvider, Renderer} from '@json-render/react';
import {z} from 'zod';

const Ops=createContext(null);
const useOps=()=>useContext(Ops);
const labels={fail:'异常',unverified:'待核验',pass:'信号恢复',adopt:'采纳',reject:'拒绝',defer:'暂缓',success:'有效',failed:'无效',recurred:'复发',unverifiedResult:'未验证'};
const types={diagnostic:'检查取证',mitigation:'临时恢复','root-cause':'根因处理',prevention:'预防复发'};
const stamp=t=>t?new Date(t*1000).toLocaleString('zh-CN',{hour12:false}):'未知';
const catalog=defineCatalog(schema,{components:Object.fromEntries(['Shell','Header','Source','IssueList','Diagnosis','Solutions','Timeline','History','Footer'].map(name=>[name,{props:z.object({}),description:`运维工作台 ${name}；只消费服务端受控数据，不执行模型命令`}])) ,actions:{}});

function useCurrent(){const {state,selected}=useOps();return state?.issues.find(i=>i.id===selected);}
const components={
 Shell:({children})=><div className="app">{children}</div>,
 Header:()=>{const {state,refresh,busy,error,message}=useOps();return <header><div className="brand"><span className="mark">W/</span><span>WIN AGENT OS <small>运维工作台 · 可运行首版</small></span></div><div className="hero"><div><p className="eyebrow">先看证据，再做决定</p><h1>红灯背后，<em>发生了什么。</em></h1><p className="sub">中文解释、互补方案、长期记录。你做决定，系统不擅自修复。</p></div><button className="primary" onClick={refresh} disabled={busy}>{busy?'正在处理…':'刷新监控证据'}</button></div><div role="status" aria-live="polite" className={error?'notice error':'notice'}>{error||message||'可请求 Eve / CPA 证据诊断 · 原规则结果保留并标注 · 不执行部署或修复'}</div><div className="metrics"><div><strong>{state?.issues.filter(x=>x.status==='fail').length??'—'}</strong><span>异常检测项</span></div><div><strong>{state?.issues.filter(x=>x.status==='unverified').length??'—'}</strong><span>待核验证据</span></div><div><strong>{state?.metrics.events??'—'}</strong><span>状态变化记录</span></div><div><strong>{state?.metrics.decisions??'—'}</strong><span>人工决定</span></div></div></header>},
 Source:()=>{const {state}=useOps();const c=state?.collector;const age=c?Math.max(c.age||0,(Date.now()/1000)-(c.refreshed||0)):0;const fresh=c?.fresh&&!c?.pollError&&age<300;return <section className={'source '+(!fresh?'warning':'')} aria-label="采集状态"><b>{fresh?'采集新鲜':'证据需核验'}</b><span>最后导入 {stamp(c?.refreshed)} · 每 30 秒只读导入现有监控</span>{c?.sourceError&&<p>{c.sourceError}</p>}{c?.pollError&&<p>{c.pollError}</p>}<details><summary>数据来源与能力边界</summary><p>{c?.source||'正在读取…'}</p><p>新鲜的是源文件心跳，不保证每项检查刚执行；认证可能沿用缓存。刷新只读取原监控的结果，不重新登录、不重启服务。检查项按源 ID 聚合，相关红灯不等于独立根因。人工“有效”反馈不是系统验证，不自动改变红灯状态。</p></details></section>},
 IssueList:()=>{const {state,selected,select,filter,setFilter}=useOps();const rows=(state?.issues||[]).filter(i=>filter==='all'||(filter==='active'?i.status!=='pass':i.status==='pass'));return <aside className="issues panel"><div className="sectionhead"><h2>问题队列</h2><span>{rows.length} 项</span></div><label className="filter">显示范围<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">异常与待核验</option><option value="all">全部历史</option><option value="pass">信号已恢复</option></select></label><nav aria-label="问题列表">{rows.map(i=><button key={i.id} className={'issue '+(selected===i.id?'selected':'')} onClick={()=>select(i.id)} aria-pressed={selected===i.id}><span className="issue-meta"><span className={'badge '+i.status}>{labels[i.status]}</span><span>{i.analysis.priority}</span></span><strong>{i.analysis.title}</strong><code>{i.id}</code></button>)}</nav>{!rows.length&&<p className="empty">此范围没有问题记录。未采样不等于健康。</p>}</aside>},
 Diagnosis:()=>{const issue=useCurrent();const {diagnose,busy,error,message}=useOps();const [question,setQuestion]=useState('');useEffect(()=>setQuestion(''),[issue?.id]);if(!issue)return <section className="panel"><h2>请选择问题</h2><p>正在读取真实监控证据。</p></section>;const a=issue.analysis;return <section className="diagnosis panel"><p className="eyebrow">01 / 中文分诊 · {a.engine}</p><div className="sectionhead"><h2>{a.title}</h2><span className={'badge '+issue.status}>{labels[issue.status]}</span></div><code>{issue.id}</code><form onSubmit={e=>{e.preventDefault();diagnose(question)}}><label className="note">向 Eve 追问<textarea maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="例如：这些红灯是否有共同原因？第一方案为什么优先？"/></label><button className="primary" disabled={busy}>{busy?'正在处理…':'请求 Eve 诊断'}</button></form><p className={'local-feedback'+(error?' error':'')} aria-live="polite">{error||message||'诊断进度和结果显示在这里；不会执行修复。'}</p><dl><dt>影响什么</dt><dd>{a.impact}</dd><dt>可能原因</dt><dd>{a.hypothesis}</dd></dl><p className="boundary">{a.confidence}。推荐排序不是实测成功率；信号恢复不代表方案已验证。</p>{a.hypotheses?.map((h,i)=><details key={i}><summary>{h.cause}</summary><p>结论状态 {h.status}</p><p>反证：{h.counterEvidence||'尚无'}</p><p>还缺什么：{h.missingEvidence||'未列出'}</p><p>证据 {h.evidenceIds.join('、')}</p></details>)}{a.hiddenIssues?.length>0&&<section><h3>还需检查的隐藏问题</h3>{a.hiddenIssues.map((h,i)=><p key={i}><b>{h.title}</b>。{h.reason}。证据 {h.evidenceIds.join('、')}</p>)}</section>}<details open><summary>直接证据</summary><pre>{issue.detail}</pre><p>源快照心跳 {stamp(issue.last_seen)} · 引擎 {a.engine}</p><p className="hash">诊断版本 {issue.revision.slice(0,16)}{a.evidence?.snapshot?' · 首次引用快照 '+a.evidence.snapshot.slice(0,16):''}</p></details></section>},
 Solutions:()=>{const issue=useCurrent();const {detail,save,busy,selected}=useOps();const [note,setNote]=useState('');useEffect(()=>setNote(''),[selected]);if(!issue)return null;return <section className="solutions panel"><p className="eyebrow">02 / 选择下一步</p><div className="sectionhead"><h2>{issue.analysis.solutions.length} 条互补路径</h2><span>不硬凑五项</span></div><p>第一项优先补齐关键证据。采纳仅记入历史，不会运行命令。</p><label className="note">决定理由 / 处理结果证据<textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：先核对进程归属；或粘贴不含密钥的验证结果。"/></label>{issue.analysis.solutions.map(s=>{const decision=detail?.decisions?.find(d=>d.revision===issue.revision&&d.solution===s.id);const outcome=detail?.outcomes?.find(d=>d.revision===issue.revision&&d.solution===s.id);return <article className="solution" key={s.id}><div className="solution-title"><span className="rank">{String(s.rank).padStart(2,'0')}</span><div><span className="kind">{types[s.kind]}{s.rank===1?' · 当前首选':''}</span><h3>{s.title}</h3></div></div><p>{s.steps}</p><details><summary>适用条件、风险、验证与回退</summary><dl><dt>适用</dt><dd>{s.applicableWhen}</dd><dt>成本</dt><dd>{s.cost}</dd><dt>风险</dt><dd>{s.risk}</dd><dt>验证</dt><dd>{s.verification}</dd><dt>回退</dt><dd>{s.rollback}</dd></dl></details><div className="actions">{['adopt','reject','defer'].map(choice=><button key={choice} disabled={busy} aria-label={`${labels[choice]}方案${s.rank}`} className={decision?.choice===choice?'chosen':''} onClick={()=>save('decision',s.id,choice,note)}>{labels[choice]}</button>)}<span>{decision?`已${labels[decision.choice]} · 未执行`:'尚未选择'}</span></div><details className="feedback"><summary>记录实际处理结果{outcome?`：${labels[outcome.result]||'未验证'}`:''}</summary><p>人工反馈，必须填写上方证据说明；不会关闭事故或覆盖监控状态。</p><div className="actions">{['success','failed','recurred','unverified'].map(result=><button key={result} disabled={busy} onClick={()=>save('outcome',s.id,result,note)}>{result==='unverified'?'未验证':labels[result]}</button>)}</div></details></article>})}</section>},
 Timeline:()=>{const {detail}=useOps();return <section className="panel timeline"><p className="eyebrow">03 / 不覆盖过去</p><h2>这个问题的历史</h2>{detail&&<><p>{detail.events.length} 次状态记录 · {detail.diagnoses.length} 个诊断版本 · {detail.decisions.length} 次决定 · {detail.outcomes.length} 次反馈</p><details><summary>诊断版本与当时证据</summary>{detail.diagnoses.map(d=><div key={d.id} className="historyrow"><b>{stamp(d.created)} · {d.id.slice(0,12)}</b><p>{d.body.hypothesis}</p><pre>{d.body.evidence?.detail||d.body.confidence}</pre><p>引擎 {d.body.engine}</p></div>)}</details>{[...detail.events.map(e=>({...e,type:'状态',text:`${labels[e.status]} · ${e.detail}`})),...detail.decisions.map(e=>({...e,type:'决定',text:`${labels[e.choice]} ${e.solution} · ${e.note||'无附注'} · 未执行`})),...detail.outcomes.map(e=>({...e,type:'人工反馈',text:`${e.result==='unverified'?'未验证':labels[e.result]} ${e.solution} · ${e.note}`}))].sort((a,b)=>b.at-a.at).slice(0,30).map((e,i)=><div className="historyrow" key={e.type+e.id+i}><small>{stamp(e.at)} · {e.type}</small><p>{e.text}</p></div>)}</>}</section>},
 History:()=>{const {search,results,busy}=useOps();const [q,setQ]=useState('');return <section className="panel archive"><p className="eyebrow">04 / 查过去怎么处理</p><h2>历史证据检索</h2><p>检索已归档的会话、提交和红灯事件。旧记录不代表当前状态。</p><form onSubmit={e=>{e.preventDefault();search(q)}}><label htmlFor="query">关键词</label><div className="searchbox"><input id="query" value={q} maxLength={120} onChange={e=>setQ(e.target.value)} placeholder="例如 maintain、login、owner"/><button disabled={busy||!q.trim()}>搜索历史</button></div></form>{results===null?<p className="empty">输入关键词，找证据，不猜原因。</p>:results.length?results.map((r,i)=><details key={i}><summary>{r.kind} · {r.id.slice(0,65)}</summary><pre>{r.text}</pre></details>):<p className="empty">没有匹配记录，不代表历史中从未发生。</p>}</section>},
 Footer:()=>{const {state}=useOps();return <footer><b>边界清楚，记录长久。</b><p>SQLite 持久化 · 仅本机访问 · 不发送通知 · 不自动修复</p><p>{state?.metrics.quality}</p><p>Eve / CPA 根据证据与历史反馈生成建议，失败不会伪装成规则成功。检测质量提升仍需独立事故集验证。</p></footer>}
};
const {registry}=defineRegistry(catalog,{components});
const spec={root:'shell',elements:{shell:{type:'Shell',props:{},children:['header','source','list','diagnosis','solutions','timeline','history','footer']},...Object.fromEntries(['Header','Source','IssueList','Diagnosis','Solutions','Timeline','History','Footer'].map((type,i)=>[['header','source','list','diagnosis','solutions','timeline','history','footer'][i],{type,props:{},children:[]}]))}};
function App(){
 const [state,setState]=useState(null),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[filter,setFilter]=useState('active'),[results,setResults]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function api(path,body){const r=await fetch(path,{headers:body?{'Content-Type':'application/json','X-CSRF-Token':state?.csrf||''}:{},method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});const value=await r.json();if(!r.ok)throw Error(value.error||'请求失败');return value;}
 async function load(){const data=await api('/api/state');setState(data);setSelected(old=>old||data.issues.find(i=>i.status!=='pass')?.id||data.issues[0]?.id);return data;}
 useEffect(()=>{let alive=true;load().catch(e=>alive&&setError(e.message));const timer=setInterval(()=>load().catch(e=>alive&&setError(e.message)),30000);return()=>{alive=false;clearInterval(timer)}},[]);
 useEffect(()=>{if(!selected)return;let active=true;setDetail(null);api('/api/issue?id='+encodeURIComponent(selected)).then(d=>active&&setDetail(d)).catch(e=>active&&setError(e.message));return()=>{active=false}},[selected,state]);
 async function run(fn){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const value={state,selected,detail,filter,setFilter,results,busy,error,message,select:setSelected,
 refresh:()=>run(async()=>{await api('/api/refresh',{});await load();setMessage('已读取现有监控；没有重新探测或修改生产服务。')}),
 search:q=>run(async()=>setResults((await api('/api/search?q='+encodeURIComponent(q))).results)),
 diagnose:question=>run(async()=>{const {runId}=await api('/api/diagnose',{issue:selected,...(question.trim()?{question}: {})});setMessage('Eve 正在 Mac mini 分析证据，结果将写入 SQLite。');const until=Date.now()+250000;while(Date.now()<until){await new Promise(resolve=>setTimeout(resolve,2000));const result=await api('/api/model-run?id='+encodeURIComponent(runId));if(result.state==='failed')throw Error(result.error||'模型诊断失败');if(result.state==='completed'){await load();setMessage('Eve 诊断已保存。归因、方案及原有历史均保留；没有执行修复。');return;}}throw Error('等待超时；诊断记录保留，刷新可查看已完成结果。')}),
 save:(kind,solution,choice,note)=>run(async()=>{const issue=state.issues.find(i=>i.id===selected);await api('/api/'+kind,{id:crypto.randomUUID(),issue:selected,revision:issue.revision,solution,[kind==='decision'?'choice':'result']:choice,note});await load();setMessage(kind==='decision'?'决定已写入 SQLite；没有执行任何修复。':'人工处理结果已保存；未改变监控状态。')})};
 return <Ops.Provider value={value}><JSONUIProvider registry={registry}><Renderer spec={spec} registry={registry}/></JSONUIProvider></Ops.Provider>;
}
createRoot(document.getElementById('root')).render(<App/>);
