import React, {createContext, useContext, useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {defineCatalog} from '@json-render/core';
import {schema} from '@json-render/react/schema';
import {defineRegistry, JSONUIProvider, Renderer} from '@json-render/react';
import {z} from 'zod';

const Context=createContext(null);
const useOps=()=>useContext(Context);
const stamp=t=>t?new Date(t*1000).toLocaleString('zh-CN',{hour12:false}):'尚无记录';
const statusNames={fail:'异常',unverified:'待核验',pass:'信号恢复'};
const resultNames={success:'有效',failed:'无效',recurred:'复发',unverified:'尚未验证'};
const priorityNames={P0:'立即协调',P1:'优先处理',P2:'安排处理',P3:'持续观察'};
const choiceNames={adopt:'采纳建议',defer:'暂缓决定',reject:'不采用'};
const hypothesisNames={confirmed:'已证实',suspected:'原因假设',unknown:'尚不清楚',rejected:'已排除'};
const triagePriorities=['P0','P1','P2','P3'];
const blastByKind={diagnostic:'只读检查面，不改业务服务',mitigation:'单一受影响服务或业务路径','root-cause':'相关认证链与依赖服务',prevention:'后续发布、验收与监控流程'};
const routeTemplates=[
 {title:'先做一次新鲜复现',kind:'diagnostic',probe:'用受控测试范围，绕开旧缓存，记录一次真实结果。',solve:'先确认问题现在是否还存在，再决定是否需要变更。',verify:'得到带实际执行时间的成功或失败证据。',rollback:'只撤掉探针，不改业务配置。'},
 {title:'核对认证材料状态',kind:'root-cause',probe:'比对认证材料版本、有效期和服务读取结果，不显示秘密值。',solve:'由凭据负责人确认材料状态，再选择轮换或重载。',verify:'负责人确认材料与目标服务匹配，登录验证恢复。',rollback:'保留旧材料和恢复窗口，变更前另行批准。'},
 {title:'核对运行实例版本',kind:'diagnostic',probe:'记录 PID、工作目录、启动时间和实际加载版本收据。',solve:'若发现运行实例落后，再按发布流程重建，不直接清理目录。',verify:'运行实例、构建产物和发布记录能够对应。',rollback:'保留原版本和启动收据，按批准的回退流程退出。'},
 {title:'做一次缓存旁路检查',kind:'mitigation',probe:'对单次受控请求标记不使用旧缓存，并保留请求时间和结果。',solve:'若只有缓存异常，修正缓存生命周期；若仍失败，回到认证链调查。',verify:'旁路结果与正常路径差异清楚，业务负责人确认影响。',rollback:'停止旁路请求，恢复原缓存路径。'},
 {title:'先启用人工业务保障',kind:'mitigation',probe:'探测登录失败对一个受控业务流程的真实影响，不扩大流量。',solve:'在根因未明时，人工受理关键业务，给维护团队留出安全窗口。',verify:'关键业务有明确受理记录，系统恢复后完成回补验收。',rollback:'确认系统恢复后关闭人工保障，保留回补记录。'},
];
function Pill({children,tone=''}){return <span className={'pill '+tone}>{children}</span>;}
function PlanDefinition({plan}){const blast=plan?.blastRadius||blastByKind[plan?.kind]||'待人工确认';return <dl>{[['方案说明',plan.steps],['适用条件',plan.applicableWhen],['影响范围',blast],['时间与资源',plan.cost],['主要风险',plan.risk],['业务验收',plan.verification],['退出与回退',plan.rollback]].map(([label,text])=><React.Fragment key={label}><dt>{label}</dt><dd>{text}</dd></React.Fragment>)}</dl>;}
function PlanDialog(){
 const {pending,setPending,saveDecision,busy,error}=useOps();const ref=useRef(null);const note=pending?.note||'',choice=pending?.choice||'defer';
 useEffect(()=>{if(pending)ref.current?.showModal();else ref.current?.close();},[Boolean(pending)]);
 return <dialog ref={ref} onCancel={()=>setPending(null)} aria-labelledby="decision-title"><div className="dialog-head"><h2 id="decision-title">确认这条处理建议</h2><button className="close-button" aria-label="关闭方案确认" onClick={()=>setPending(null)}>×</button></div>{pending&&<form onSubmit={e=>{e.preventDefault();saveDecision(pending,choice,note);}}><div className="dialog-body"><div className="summary-box"><h2>{pending.plan.title}</h2><p>{pending.plan.rationale||pending.plan.steps}</p></div><PlanDefinition plan={pending.plan}/><label className="field" htmlFor="decision-choice">你的决定</label><select id="decision-choice" value={choice} onChange={e=>setPending({...pending,choice:e.target.value})}>{Object.entries(choiceNames).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><label className="field" htmlFor="reason">为什么这样决定？</label><textarea id="reason" value={note} onChange={e=>setPending({...pending,note:e.target.value})} maxLength={1000} required placeholder="写明选择依据。保存后进入真实 SQLite 历史，但不会执行修复。"/><p className="error" aria-live="polite">{error}</p><p className="small-note">仅保存决定。不批准执行、不改变红灯、不操作业务服务。</p></div><div className="dialog-footer"><button type="button" onClick={()=>setPending(null)}>返回比较</button><button className="primary" disabled={busy||!note.trim()}>确认保存决定</button></div></form>}</dialog>;
}
function solutionPaths(analysis,detail){
 const model=analysis?.engine==='eve-cpa-1'&&Array.isArray(analysis.solutions)?analysis.solutions:[];
 const baselineDiagnosis=detail?.diagnoses?.find(item=>item.body?.engine==='rules-1');
 const baseline=baselineDiagnosis?.body?.solutions||(!analysis||analysis.engine!=='eve-cpa-1'?analysis?.solutions||[]:[]);
 return routeTemplates.map((template,index)=>{const plan=model[index]||baseline[index]||null;const source=model[index]?'Eve 真实输出':baseline[index]?'规则基线':'待 Agent 补齐';return {...template,title:plan?.title||template.title,summary:plan?.rationale||plan?.steps||template.solve,plan,source,blast:plan?.blastRadius||blastByKind[plan?.kind]||'待人工确认',applicable:plan?.applicableWhen||'需要人工确认适用条件。',risk:plan?.risk||'影响范围和副作用需要人工确认。',actionable:Boolean(model[index]||(analysis?.engine!=='eve-cpa-1'&&baseline[index]))};});
}
function IssueDocument(){
 const {state,issue,analysis,setPlanId,busy,diagnose,question,setQuestion,setPage,selectIssue,detail,notice,saveDecision,refresh}=useOps();
 const [askOpen,setAskOpen]=useState(false),[probePhase,setProbePhase]=useState('idle'),[probeStep,setProbeStep]=useState(-1),[feedback,setFeedback]=useState(''),[feedbackText,setFeedbackText]=useState(''),[pathIndex,setPathIndex]=useState(0),[decisionNote,setDecisionNote]=useState(''),[decision,setDecision]=useState(null),[localNotice,setLocalNotice]=useState('');
 const askRef=useRef(null),triggerRef=useRef(null),timers=useRef([]);
 useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 useEffect(()=>{timers.current.forEach(clearTimeout);timers.current=[];setPathIndex(0);setProbePhase('idle');setProbeStep(-1);setFeedback('');setFeedbackText('');setDecisionNote('');setDecision(null);setLocalNotice('');},[issue?.id,issue?.revision]);
 useEffect(()=>{const dialog=askRef.current;if(!dialog)return;if(askOpen&&!dialog.open){dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('[data-ask-approve]')?.focus());}if(!askOpen&&dialog.open)dialog.close();if(!askOpen)triggerRef.current?.focus?.();},[askOpen]);
 if(!issue)return <><h1>正在读取监控</h1><p className="muted">没有数据时不推断业务健康。</p></>;
 const leader=analysis?.engine==='eve-cpa-1'||analysis?.audience==='leadership-v1';
 const paths=solutionPaths(analysis,detail),activePath=paths[pathIndex]||paths[0],issues=state?.issues||[];
 function openProbeAsk(){triggerRef.current=document.activeElement;setAskOpen(true);}
 function startProbe(){timers.current.forEach(clearTimeout);timers.current=[];setProbePhase('running');setProbeStep(0);setLocalNotice('Agent 已接手问题，开始寻找复现；不会直接执行修复。');const messages=['Agent 已读取问题、优先级和证据边界。','探针已加入当前处理流程。','Agent 正在寻找一次受控复现。','等待人工反馈：问题已复现、问题已解决或输入反馈。'];messages.slice(1).forEach((message,index)=>timers.current.push(setTimeout(()=>{setProbeStep(index+1);setLocalNotice(message);if(index===messages.length-2)setProbePhase('feedback');},(index+1)*650)));}
 function onFeedback(kind){setFeedback(kind);setFeedbackText('');setLocalNotice(kind==='reproduced'?'反馈已记录：问题已复现。':kind==='solved'?'反馈已记录：问题已解决。':'等待自定义反馈。');}
 function saveTyped(){if(!feedbackText.trim()){setLocalNotice('请先输入反馈。');return;}setFeedback('typed');setLocalNotice('反馈已记录：自定义文字。');}
 async function applyChoice(choice='adopt'){if(!activePath?.plan||!activePath.actionable){setLocalNotice('当前路线不是可保存的诊断版本，请先生成领导简报。');return;}if(!decisionNote.trim()){setLocalNotice('请先写决定理由。');return;}const ok=await saveDecision({issue:issue.id,revision:issue.revision,plan:activePath.plan},choice,decisionNote.trim());if(ok){setDecision({choice,route:activePath.title,note:decisionNote.trim()});setDecisionNote('');setLocalNotice(choice==='adopt'?'已记录采纳；执行仍由团队手工完成。':'已记录暂缓；没有执行修复。');}}
 const raw={source:'legacy-monitor',issue:issue.id,status:issue.status,detail:issue.detail,snapshotHeartbeat:issue.last_seen,revision:issue.revision,events:(detail?.events||[]).slice(0,12),note:'保存记录不是新鲜实测。'};
 return <><div className="funnel-real">
  <header className="funnel-real-head"><div><div className="funnel-mark">TRIAGE FUNNEL / REAL APP</div><div className="kicker"><span>{issue.id}</span><Pill tone={issue.status==='fail'?'red':''}>{statusNames[issue.status]}</Pill><Pill tone={leader?'blue':''}>{leader?'Eve 领导简报':'规则分诊，可重新分析'}</Pill></div><h1>{analysis.title}</h1><p className="lead">{analysis.impact}</p><p className="small muted">只读监控证据。Agent 建议，人工决定；此页不执行业务修复。</p></div><div className="real-safety">只读业务<br/>不自动修复</div></header>
  <div className="real-flow-line"><a href="#triage-real">01 TRIAGE</a><span></span><a href="#probe-real">02 PROBE · ONE GATE</a><span></span><a href="#route-real">03 ROUTE &amp; APPLY</a></div>
  <section id="triage-real" className="funnel-stage"><div className="funnel-stage-title"><div><h2>1. Agent 分诊</h2><p>长日志变成问题标题、描述和 P0-P3。人只选一个继续。</p></div><Pill>{issues.length} 个问题</Pill></div><details className="raw-log"><summary>原始监控日志（默认收起）</summary><pre className="evidence-raw">{JSON.stringify(raw,null,2)}</pre></details><div className="triage-lanes">{triagePriorities.map(priority=>{const items=issues.filter(item=>(item.analysis?.priority||'P2')===priority);return <div className={'triage-lane '+priority.toLowerCase()} key={priority}><div><b>{priority}</b><span>{priorityNames[priority]||'观察'}</span></div>{items.length?items.map(item=><button key={item.id} data-issue-id={item.id} aria-current={item.id===issue.id?'true':'false'} onClick={()=>selectIssue(item.id)}><strong>{item.analysis?.title||item.id}</strong><small>{item.analysis?.impact||'Agent 尚未补齐描述。'}</small></button>):<em>暂无问题</em>}</div>})}</div><div className="selected-real"><strong>当前问题：{analysis.title}</strong><span>{issue.id} · {analysis.priority}</span><p>{analysis.impact}</p></div><div className="stage-actions"><button onClick={refresh} disabled={busy}>刷新证据</button><button className="primary" onClick={()=>diagnose(question)} disabled={busy}>{busy?'Agent 分析中…':'让 Eve 整理当前问题'}</button><span className="small-note">{notice}</span></div></section>
  <section id="probe-real" className="funnel-stage"><div className="funnel-stage-title"><div><h2>2. Probe · 一次审批门</h2><p>点击添加探针后只问一次 AskUserQuestion。批准后自动走完整 Agent steps。</p></div><Pill tone="blue">ONE GATE</Pill></div><div className="probe-real-card"><div className="probe-real-copy"><span className="mono-label">PROBE WORKFLOW</span><h3>{probePhase==='idle'?'准备添加探针':probePhase==='running'?'Agent 正在处理…':'等待人工反馈'}</h3><p>{probePhase==='idle'?'探针只查复现，不修业务。':probePhase==='running'?'步骤实时显示，避免黑盒等待。':'反馈进入下一轮分诊，不自动关闭问题。'}</p></div>{probePhase!=='idle'&&<div className="agent-step-list">{['读取问题','自动添加探针','寻找复现','等待人工反馈'].map((label,index)=><div className={'agent-step '+(probeStep>index?'done':probeStep===index?'active':'pending')} key={label}><span>{probeStep>index?'✓':index+1}</span><div><strong>{label}</strong><small>{['锁定标题、优先级和证据边界。','探针已加入处理流程。','等待一次受控结果。','人选择复现、解决或补充说明。'][index]}</small></div></div>)}</div>}<pre className="probe-code">{`probe({
  issue: "${issue.id}",
  freshResult: true,
  record: ["executedAt", "listenerCwd", "loadedVersion"],
  maxAttempts: 1
})`}</pre>{probePhase==='idle'&&<button className="primary" onClick={openProbeAsk}>添加探针</button>}{probePhase==='feedback'&&<div className="feedback-real"><div><button onClick={()=>onFeedback('reproduced')}>问题已复现</button><button onClick={()=>onFeedback('solved')}>问题已解决</button><button onClick={()=>onFeedback('typed')}>输入反馈</button></div>{feedback==='typed'&&<><textarea aria-label="自定义反馈" value={feedbackText} onChange={e=>setFeedbackText(e.target.value)} placeholder="告诉 Agent 下一轮要注意什么"></textarea><button onClick={saveTyped}>保存文字反馈</button></>}{feedback&&feedback!=='typed'&&<p>{feedback==='reproduced'?'反馈已记录：问题已复现。':'反馈已记录：问题已解决。'}</p>}{feedback==='typed'&&feedbackText&&<p>反馈已记录：自定义文字。</p>}</div>}</div><p className="busy-note" aria-live="polite">{localNotice}</p></section>
  <section id="route-real" className="funnel-stage"><div className="funnel-stage-title"><div><h2>3. Route &amp; Apply Fix</h2><p>Agent 给 5 条路线。每条显示探针、解决、Blast Radius、验收和回退。</p></div><Pill tone="blue">HUMAN CHOICE</Pill></div><div className="real-route-list">{paths.map((path,index)=><div className={'real-route '+(index===pathIndex?'selected':'')} key={path.id}><button className="real-route-head" data-route-index={index} onClick={()=>{setPathIndex(index);if(path.plan)setPlanId(path.plan.id);else setPlanId('');setDecisionNote('');}}><span>{String(index+1).padStart(2,'0')}</span><strong>{path.title}<small>{path.summary}</small></strong><em><b>BLAST RADIUS</b>{path.blast}<i>{path.source}</i></em><mark>{index===pathIndex?'−':'+'}</mark></button>{index===pathIndex&&<div className="real-route-detail"><div><span>复现探针</span><p>{path.probe}</p></div><div><span>解决动作</span><p>{path.solve}</p></div><div><span>影响范围</span><p>{path.blast}</p></div><div><span>验收</span><p>{path.verify}</p></div><div><span>回退</span><p>{path.rollback}</p></div><div><span>边界</span><p>{path.applicable} {path.risk}</p></div></div>}</div>)}</div><div className="real-apply"><h3>人来应用路线</h3><p>点击后只记录人工采纳，实际执行由团队手工完成。没有第二个审批弹窗。</p><div className="selected-real"><strong>{activePath?.title}</strong><span>Blast Radius：{activePath?.blast}</span></div><label className="field" htmlFor="decision-note">决定理由</label><textarea id="decision-note" value={decisionNote} onChange={e=>setDecisionNote(e.target.value)} maxLength={1000} placeholder="例如：先采用最小范围探针，等结果再处理。"></textarea><div className="decision-actions"><button className="primary" disabled={busy} onClick={()=>applyChoice('adopt')}>应用这条路线（只记录）</button><button disabled={busy} onClick={()=>applyChoice('defer')}>暂缓</button></div>{decision&&<p className="decision-saved">已记录：{choiceNames[decision.choice]||decision.choice} · {decision.route}<br/>理由：{decision.note}</p>}</div></section>
 </div><dialog ref={askRef} className="probe-dialog" onCancel={e=>{e.preventDefault();setAskOpen(false);}} aria-labelledby="probe-ask-title" aria-describedby="probe-ask-description"><div className="probe-dialog-card"><div className="dialog-head"><span>AskUserQuestion</span><button type="button" aria-label="关闭" onClick={()=>setAskOpen(false)}>×</button></div><p className="one-gate">ONE APPROVAL GATE</p><h2 id="probe-ask-title">允许 Agent 添加探针？</h2><p id="probe-ask-description">批准后，Agent 自动添加一次最小复现探针，展示步骤并等待人工反馈。不会直接修复业务。</p><div className="probe-dialog-target"><span>当前问题</span><strong>{analysis.title}</strong></div><div className="dialog-footer"><button type="button" onClick={()=>setAskOpen(false)}>取消</button><button type="button" className="primary" data-ask-approve onClick={()=>{setAskOpen(false);startProbe();}}>批准并开始</button></div></div></dialog></>;
}
function HistoryDocument(){const {issue,detail,setPage,busy,saveOutcome}=useOps();const [note,setNote]=useState(''),[result,setResult]=useState('unverified'),[solution,setSolution]=useState('');
 useEffect(()=>{setNote('');setSolution('');setResult('unverified');},[issue?.id,issue?.revision]);
 const options=issue?.analysis.solutions||[],selected=solution||options[0]?.id;
 return <><div className="kicker">{issue?.id}</div><h1>决策记录</h1><p className="lead">保存当时的证据、判断和方案，再记录后来有没有用。</p><div className="audit-strip">真实 SQLite 历史。模型生成、人工选择与实际处理结果分开保存。</div>
 {issue&&<section className="section"><h2>补充处理结果</h2><p className="small muted">仅记录真实处理情况。没有执行过的方案请选择“尚未验证”。</p><form onSubmit={e=>{e.preventDefault();saveOutcome(selected,result,note).then(ok=>{if(ok)setNote('');});}}><label className="field" htmlFor="outcome-plan">反馈针对的当前方案</label><select id="outcome-plan" value={selected||''} onChange={e=>setSolution(e.target.value)}>{options.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><label className="field" htmlFor="result">结果类型</label><select id="result" value={result} onChange={e=>setResult(e.target.value)}>{Object.entries(resultNames).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><label className="field" htmlFor="outcome-note">业务验证或复发说明</label><textarea id="outcome-note" required value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/><div className="plan-footer"><span>人工反馈不自动改变监控状态。</span><button className="primary" disabled={busy||!note.trim()}>保存处理反馈</button></div></form></section>}
 <section className="section" id="history-list"><div className="section-title"><h2>完整时间线</h2><Pill>{detail?.diagnoses?.length??0} 个诊断版本</Pill></div><div className="timeline">{detail?.diagnoses?.slice(0,20).map(d=><article className="event" key={d.id} data-diagnosis-id={d.id}><time>{stamp(d.created)}</time><strong>{d.body.title}</strong><p>{d.body.hypothesis}</p><Pill tone={d.body.audience==='leadership-v1'?'blue':''}>{d.body.audience==='leadership-v1'?'Eve 领导简报':d.body.engine}</Pill><p className="small-note">版本 {d.id.slice(0,16)} · {(d.body.solutions||[]).length} 条候选</p></article>)}</div>{(detail?.diagnoses?.length||0)>20&&<p className="small-note">显示最近二十个版本，全部历史仍保留在 SQLite。</p>}
 {detail?.decisions?.map(d=><article className="event" key={d.id}><time>{stamp(d.at)} · 决定</time><strong>{choiceNames[d.choice]}</strong><p>{d.note}</p><Pill>仅记录 · 未执行</Pill></article>)}{detail?.outcomes?.map(d=><article className="event" key={d.id}><time>{stamp(d.at)} · 人工反馈</time><strong>{resultNames[d.result]}</strong><p>{d.note}</p></article>)}</section><button className="text-button" onClick={()=>setPage('issue')}>返回当前问题</button></>;
}
function QualityDocument(){const {quality,diagnose,busy,selectIssue}=useOps();const q=quality;return <><h1>复盘与发现</h1><p className="lead">用真实处理结果检验建议，不能把诊断次数当作准确率。</p><div className="quality-grid"><section className="quality-card"><p>已保存的模型诊断</p><p className="number">{q?.runs.completed??0}</p><p>来自真实 SQLite 运行记录。</p></section><section className="quality-card"><p>人工结果反馈</p><p className="number">{Object.values(q?.outcomes||{}).reduce((a,b)=>a+b,0)}</p><p>无效 {q?.outcomes.failed??0} · 复发 {q?.outcomes.recurred??0}</p></section></div><div className="summary-box"><h2>真实推荐质量尚未测量</h2><p>{q?.note||'正在读取评测依据。'}</p></div><section className="section"><h2>当前证据中的潜在风险候选</h2><p className="muted small">这些是已保存的模型判断，尚不等于确认故障。没有另一个自动扫描器。</p>{(q?.hiddenCandidates||[]).map((x,i)=><div className="fact" key={i}><h3>{x.title}</h3><p>{x.reason}</p><button className="text-button" onClick={()=>selectIssue(x.issue)}>查看关联问题</button></div>)}{!q?.hiddenCandidates?.length&&<p className="empty">当前保存的诊断未提出其他风险候选。没有候选不代表不存在问题。</p>}<button className="primary" disabled={busy} onClick={()=>diagnose('请重点检查现有证据中是否存在表面正常但业务异常的风险。区分已确认事实与待核实候选，不编造隐藏问题；按领导决策方式给出独立方案。')}>重新分析当前问题</button></section><section className="section"><h2>质量提升需要什么证据</h2><ul className="method-list"><li>绑定当时第一推荐的反馈。目前有 {q?.firstRecommendationFeedback??0} 条，但仍需独立核实结果。</li><li>覆盖真实故障与正常对照案例，分别测量误报和漏报。</li><li>同条件比较不同建议版本，再判断前五方案是否更充分。</li></ul><p className="small-note">自动优化、独立标注集与评测晋级尚未接入，不展示虚构百分比。</p></section></>;}
const components={
 Shell:({children})=>{const {state,error}=useOps();const c=state?.collector;return <><div className="prototype"><b>真实运维工作台 · 领导决策版</b><span>{c?.fresh?'监控快照新鲜':'证据需要核验'} · SQLite 持久化 · 不自动修复{error?' · 有操作未完成':''}</span></div><div className="layout">{children}</div><PlanDialog/></>},
 Sidebar:()=>{const {state,selected,selectIssue,page,setPage,query,setQuery,refresh,busy,exportHistory}=useOps();const rows=(state?.issues||[]).filter(i=>[i.id,i.analysis.title].join(' ').includes(query));return <aside className="sidebar" aria-label="业务工作区"><div className="brand"><span className="brand-icon">W</span><div><b>运行简报</b><small>WIN AGENT OS</small></div></div><div className="workspace-label">业务工作区 <span>真实连接</span></div><nav className="side-nav" aria-label="工作区">{[['issue','待决策','▣'],['history','决策记录','◷'],['quality','复盘与发现','◇']].map(([key,label,icon])=><button key={key} aria-pressed={page===key} onClick={()=>setPage(key)} data-page={key}><span className="glyph" aria-hidden="true">{icon}</span>{label}</button>)}</nav><section aria-label="关注事项"><div className="queue-title"><span>关注事项</span><span>{rows.length}</span></div><label className="small muted" htmlFor="search">查找问题</label><input id="search" type="search" className="queue-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="按业务问题或检测项查找"/><div className="issues">{rows.map(i=><button className="issue-item" key={i.id} data-issue-id={i.id} aria-pressed={selected===i.id} onClick={()=>selectIssue(i.id)}><span className="issue-line"><span className={'status-dot '+(i.status==='fail'?'':'candidate-dot')}/>{i.analysis.title}</span><small>{statusNames[i.status]} · {i.id}</small></button>)}{!rows.length&&<p className="small muted">当前范围没有匹配项；不据此认定业务健康。</p>}</div></section><div className="side-bottom"><button className="ghost" onClick={refresh} disabled={busy}>刷新监控证据</button><button className="ghost" onClick={exportHistory} disabled={!selected}>导出当前问题记录</button><p className="small-note">只读原监控，不启动第二个采集器。</p></div></aside>},
 Product:({children})=>{const {page,setPage,notice,error}=useOps();const jump=id=>{setPage('issue');setTimeout(()=>{const e=document.getElementById(id);if(e){if(id==='evidence')e.open=true;e.scrollIntoView({block:'start'});}},50);};return <section className="product" aria-label="业务决策工作台"><header className="toolbar"><div className="breadcrumb">业务工作区 <strong>{({issue:'待决策',history:'决策记录',quality:'复盘与发现'})[page]}</strong></div><span className="toolbar-state">三步分诊流程 · REAL APP</span></header><div className="notification" role="status">{error||notice}</div>{children}<footer className="origins">真实监控、Eve / CPA 与 SQLite 已连接。新鲜心跳不证明每项检查重新执行；人工选择不等于修复完成。<br/>设计来自已批准的领导版 V3；原型假数据未接入此应用。</footer></section>},
 Reading:({children})=><div className="reading">{children}</div>,
 Document:()=>{const {page}=useOps();return <main className="document" id="content">{page==='issue'?<IssueDocument/>:page==='history'?<HistoryDocument/>:<QualityDocument/>}</main>},
 Inspector:()=>{const {issue,analysis,plan,detail,setPage,state,page}=useOps();const last=detail?.decisions?.[0];if(page==='issue')return null;return <aside className="inspector" aria-label="问题属性与当前建议"><div><h2>事项属性</h2>{[['状态',issue?statusNames[issue.status]:'读取中'],['优先级',priorityNames[analysis?.priority]||'待判断'],['源快照心跳',stamp(issue?.last_seen)],['判断来源',analysis?.audience==='leadership-v1'?'Eve 领导简报':analysis?.engine||'尚无'],['责任判断','尚不能据此归责到个人']].map(([label,value])=><div className="property" key={label}><span className="label">{label}</span><strong>{value}</strong></div>)}<hr/><div className="property"><span className="label">当前试选</span><p className="chosen-name">{plan?.title||'暂无方案'}</p><p className="small muted">试选不等于保存，也不等于执行。</p></div><div className="property"><span className="label">最近保存的决定</span><p>{last?choiceNames[last.choice]:'尚未保存'}</p>{last&&<Pill>未执行</Pill>}</div><section className="review-entry"><hr/><h3>给下一次判断留依据</h3><p className="small muted">记录真实处理结果，复核无效建议和复发。</p><button onClick={()=>setPage('history')}>记录结果与复发</button><button onClick={()=>setPage('quality')}>查看复盘与潜在风险</button><p className="small-note">当前累计 {state?.metrics.events??0} 条状态变化。全部历史保存在 SQLite。</p></section></div></aside>}
};
const catalog=defineCatalog(schema,{components:Object.fromEntries(Object.keys(components).map(name=>[name,{props:z.object({}),description:'真实运维界面 '+name}])) ,actions:{}});
const {registry}=defineRegistry(catalog,{components});
const spec={root:'shell',elements:{shell:{type:'Shell',props:{},children:['sidebar','product']},sidebar:{type:'Sidebar',props:{},children:[]},product:{type:'Product',props:{},children:['reading']},reading:{type:'Reading',props:{},children:['document','inspector']},document:{type:'Document',props:{},children:[]},inspector:{type:'Inspector',props:{},children:[]}}};
function App(){
 const [state,setState]=useState(null),[selected,setSelected]=useState(null),[page,setPage]=useState('issue'),[query,setQuery]=useState(''),[detail,setDetail]=useState(null),[quality,setQuality]=useState(null),[planId,setPlanId]=useState(''),[question,setQuestion]=useState(''),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('正在读取真实监控证据。');
 const csrf=useRef('');const running=useRef(false);const issue=state?.issues.find(i=>i.id===selected),analysis=issue?.analysis,plan=analysis?.solutions.find(s=>s.id===planId)||analysis?.solutions[0];
 async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf.current}:{},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Error(x.error||'请求失败');return x;}
 async function load(){const x=await api('/api/state');csrf.current=x.csrf;setState(x);setSelected(id=>x.issues.some(i=>i.id===id)?id:x.issues.find(i=>i.status!=='pass')?.id||x.issues[0]?.id);return x;}
 useEffect(()=>{let live=true;load().then(()=>live&&setNotice('已读取真实监控。可生成领导简报，不执行修复。')).catch(e=>live&&setError(e.message));const timer=setInterval(()=>load().catch(e=>live&&setError(e.message)),30000);return()=>{live=false;clearInterval(timer);};},[]);
 useEffect(()=>{if(!selected)return;let live=true;api('/api/issue?id='+encodeURIComponent(selected)).then(x=>live&&setDetail(x)).catch(e=>live&&setError(e.message));return()=>{live=false;};},[selected,state]);
 useEffect(()=>{let live=true;if(page==='quality')api('/api/quality').then(x=>live&&setQuality(x)).catch(e=>live&&setError(e.message));return()=>{live=false;};},[page,state]);
 useEffect(()=>{setQuestion('');setPlanId('');setDetail(null);},[selected]);
 async function run(fn){if(running.current)return false;running.current=true;setBusy(true);setError('');try{await fn();return true;}catch(e){setError(e.message);return false;}finally{running.current=false;setBusy(false);}}
 const selectIssue=id=>{setSelected(id);setPage('issue');};
 const diagnose=q=>run(async()=>{const id=selected;if(!id)throw Error('请先选择问题');setPage('issue');const r=await api('/api/diagnose',{issue:id,question:q.trim()||'请为非技术领导生成业务简报：影响、紧急程度、事实与推测、协调范围；最多五条彼此独立的处理路线，不要操作步骤。'});setNotice('Eve 正在分析真实证据与历史，完成后写入 SQLite。');const until=Date.now()+250000;while(Date.now()<until){await new Promise(resolve=>setTimeout(resolve,2000));const x=await api('/api/model-run?id='+encodeURIComponent(r.runId));if(x.state==='failed')throw Error(x.error||'模型诊断失败');if(x.state==='completed'){await load();setNotice('领导简报已保存到 SQLite；未执行任何修复。');return;}}throw Error('等待超时。运行记录已保留，可刷新查看；未返回假结果。');});
 const saveDecision=(snapshot,choice,note)=>run(async()=>{if(!note.trim())throw Error('请填写决定理由');await api('/api/decision',{id:crypto.randomUUID(),issue:snapshot.issue,revision:snapshot.revision,solution:snapshot.plan.id,choice,note});setPending(null);await load();setNotice('决定已写入真实 SQLite；未执行修复。');});
 const saveOutcome=(solution,result,note)=>run(async()=>{if(!note.trim())throw Error('请填写验证说明');await api('/api/outcome',{id:crypto.randomUUID(),issue:selected,revision:issue.revision,solution,result,note});await load();setNotice('人工结果反馈已保存；监控状态未被改写。');});
 const refresh=()=>run(async()=>{await api('/api/refresh',{});await load();setNotice('已刷新现有监控证据，没有重新登录或重启业务服务。');});
 const exportHistory=()=>run(async()=>{const data=await api('/api/issue?id='+encodeURIComponent(selected));const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ops-issue-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 return <Context.Provider value={{state,selected,selectIssue,page,setPage,query,setQuery,issue,analysis,plan,planId,setPlanId,question,setQuestion,pending,setPending,busy,error,notice,detail,quality,diagnose,saveDecision,saveOutcome,refresh,exportHistory}}><JSONUIProvider registry={registry}><Renderer spec={spec} registry={registry}/></JSONUIProvider></Context.Provider>;
}
createRoot(document.getElementById('root')).render(<App/>);
